import { db } from "@/lib/db";
import * as React from "react";

type MetadataProps = {
  params: {
    username: string;
  };
};

export async function generateMetadata({ params }: MetadataProps) {
  const user = await db.user.findUnique({
    where: {
      username: `@${params.username}`,
    },
  });

  if (user) {
    return {
      title: `${user.name} (${user.username}) / X`,
      description: `${user.name} profile`,
      referrer: "no-referrer",
    };
  }

  return {
    title: "Home / X",
    description: "Generated by create next app",
    referrer: "no-referrer",
  };
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
