import Providers from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { Toaster } from "sonner";

const sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Home / X",
  description: "Generated by create next app",
  referrer: "no-referrer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark antialiased">
      <body className={sans.className}>
        <Providers>
          <div id="reply-container" />
          <main className="min-h-screen w-full">
            <Toaster richColors />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
